### ISSUE TITLE
Trocar a ordem de declaração do style.css e bootstrap.css

### ISSUE THREAD

**Issue by biancarosa** [insideoutprojectbr/mulheres-palestrantes#10]
O bootstrap deveria vir antes pra possibilitar qualquer override. Tive que jogar um important na navbar que não deveria ser necessário.

Mas só alterar quebra o layout, então tem que ver com algum tempo pra consertar os detalhes.

**Comment by darlenedms** [comment]
@biancarosa removi o Bootstrap :stuck_out_tongue_winking_eye:
