### ISSUE TITLE
Incluir Palestrante

### ISSUE THREAD

**Issue by arianizac** [insideoutprojectbr/mulheres-palestrantes#21]
Olá, gostaria de pedir para me incluírem na relação de palestrantes:

{"name":"Ariane Izac","interests":["Testes de Software, Automação, Qualidade de software"],"location":"Campinas/SP","photo":null,"email"afizac@gmail.com,"linkedin"ariane-izac,"github":null,"twitter"arianizac,"fb":null}

obs: Não sei como faria para referenciar a foto para enviar para vcs rs

**Comment by samycici** [comment]
@arianizac você tem gravatar (https://en.gravatar.com/)? É o mesmo e-mail do gmail? Nós usamos a imagem seguindo a documentação do gravatar https://br.gravatar.com/site/implement/images/

**Comment by arianizac** [comment]
Seria esse o link que vcs precisam?
http://2.gravatar.com/avatar/14958fc6544edc07d96d33d6b6ba6a0b

**Comment by biancarosa** [comment]
Adicionada! :)

A foto é adicionada automaticamente através do email, se for o mesmo email do Gravatar. Funcionou certinho.
