### ISSUE TITLE
adicionar 

### ISSUE THREAD

**Issue by julianafelix** [insideoutprojectbr/mulheres-palestrantes#28]
nome: juliana felix nunes
interesse: TI verde, Software livre, gerenciamento de TI
cidade: Goiania/GO
email: juliana_fenunes@gmail.com
twitter: www.twitter.com/juh_felix
fb: www.facebook.com/juliana.felix.nunes
linkedin: https://www.linkedin.com/in/julianafelixnunes

**Comment by darlenedms** [comment]
Obrigada pela contribuição, meninas *-*
