### ISSUE TITLE
Logos das redes sociais arredondados

### ISSUE THREAD

**Issue by dayanyrec** [insideoutprojectbr/mulheres-palestrantes#34]
Não sei se era o objetivo inicial mas todas as imagens dentro dos cards estão com bordas arredondadas. Porém, não é permitido modificar os logos. O LinkedIn, por exemplo, deixa isso claro em https://brand.linkedin.com/visual-identity/logo
Podemos manter só a foto do perfil arredondada. O que acham?

**Comment by darlenedms** [comment]
Podemos trocar pelo FontAwesome https://fortawesome.github.io/Font-Awesome/
