### ISSUE TITLE
Cards desalinhados no safari

### ISSUE THREAD

**Issue by samycici** [insideoutprojectbr/mulheres-palestrantes#43]
recebi por e-mail:

"Uma dica de layout é navegando pelo safari, os cards ficaram desalinhados (segue a imagem anexa), mas isso não acontece no chrome. Acho que o site fica mais limpo se tirar o "border-bottom:4px solid #861028" do header também. Eu tentei mudar os tamanhos de fontes do header pra testar, mas não consegui."

<img width="1224" alt="captura de tela 2016-07-15 as 16 57 28" src="https://cloud.githubusercontent.com/assets/3614317/16886891/3d1d2b4a-4aad-11e6-9e09-591244b08b31.png">

**Comment by darlenedms** [comment]
@samycici Pode revalidar o layout no Safari?

Sobre a borda do header gostaria de saber a opinião das outras meninas, convoco @annacruz @biancarosa @dayanyrec @pgrangeiro @rai200890

**Comment by annacruz** [comment]
Testei aqui no meu safari e está ok, mas seira bom alguém rever.

![Tela no meu safari](https://cloud.githubusercontent.com/assets/111924/17087760/b011a02c-51e7-11e6-84f1-1a9a7dc9ebb1.png)

Quanto a barra preta, acho que ela poderia ser um pouco mais fina.

**Comment by samycici** [comment]
Safari Ok!
