### ISSUE TITLE
Inclusão na lista

### ISSUE THREAD

**Issue by tinascherrer** [insideoutprojectbr/mulheres-palestrantes#57]
Olá, gostaria de entrar para a lista, podem me ajudar, por favor? Obrigada!

**Comment by darlenedms** [comment]
Olá @tinascherrer
Para incluí-la na lista precisamos das seguintes informações:
Nome, lista de assuntos, cidade, url da foto, email e redes sociais (linkedin, github, twitter e facebook) se tiver.

Você pode colocar as informações aqui, assim podemos adicioná-la, ou pode fazer um pull request alterando o arquivo [mulheres.json](https://github.com/insideoutprojectbr/mulheres-palestrantes/blob/master/mulheres.json) (mais informações no [CONTRIBUTING](https://github.com/insideoutprojectbr/mulheres-palestrantes/blob/master/CONTRIBUTING.md)).

Qualquer dúvida é só falar :smile:

**Comment by tinascherrer** [comment]
Olá, obrigada, Darlene!

Seguem as informações:

Nome: Martina Scherrer

Assuntos: Marketing Digital, Mídias Sociais, Publicidade e Propaganda,
Planejamento Estratégico e de Comunicação, Empreendedorismo

Cidade: Porto Alegre - RS

Foto: https://en.gravatar.com/fragmentosdeconversa

E-mail: tinscherrer@gmail.com

Redes Sociais:
facebook.com/ScherrerTina
linkedin.com/in/martinascherrer
twitter.com/tinascherrer
github.com/tinascherrer

Podes, por favor, confirmar a inserção?
Muito obrigada!

Beijos, Martina.

2016-09-29 20:34 GMT-06:00 Darlene Medeiros <notifications@github.com>:

**Comment by darlenedms** [comment]
Já pode conferir no [site](http://insideoutproject.xyz/mulheres-palestrantes/) @tinascherrer 😄  
Obrigada pela contribuição! ❤️

**Comment by tinascherrer** [comment]
Ficou lindo, obrigada!
Desculpa, eu li as instruções, mas não tive certeza de como fazer, então
achei melhor pedir ajuda pra não fazer bobagem, heheh.
Valeu!

2016-10-03 14:42 GMT-06:00 Darlene Medeiros <notifications@github.com>:
