### ISSUE TITLE
Explicar a estrutura do arquivo mulheres.json

### ISSUE THREAD

**Issue by rai200890** [insideoutprojectbr/mulheres-palestrantes#6]
Explicar com detalhes a estrutura do arquivo no Readme, como os avatares são recuperados, etc.
Campos obrigatórios:
- name
- email

**Comment by biancarosa** [comment]
Já adicionei mais algumas informações.

Vocês acham necessário detalhar a estrutura toda? Deixei aberta a opção pra quem não souber como fazer abrir um issue pedindo a inclusão... Supondo que a pessoa não saiba git, acho uma boa opção.

**Comment by darlenedms** [comment]
Acredito que os campos são auto-explicativos, por mim está ótimo :)

**Comment by annacruz** [comment]
Vai detalhar mais alguma coisa? pra mim parece bom... posso fechar a issue?

**Comment by biancarosa** [comment]
Vai na fé! Por mim pode fechar.

On Wed, Oct 28, 2015 at 5:38 PM, Anna Cruz <notifications@github.com> wrote:

> Vai detalhar mais alguma coisa? pra mim parece bom... posso fechar a issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/insideoutprojectbr/mulheres-palestrantes/issues/6#issuecomment-151967521>
> .
>



-- 
{}'s
*Bianca Rosa*
(21) 98750-1039

**Comment by annacruz** [comment]
Fechado pq geral concordou que não tem sentido explicar mais do que já foi explicado.
