### ISSUE TITLE
Fixar rodapé

### ISSUE THREAD

**Issue by darlenedms** [insideoutprojectbr/mulheres-palestrantes#8]
Quando a busca não encontra nenhuma mulher para o termo pesquisado o rodapé sobe, ficando no meio da página.

**Comment by dayanyrec** [comment]
me parece que essa issue pode ser fechada. confere, @darlenedms?

**Comment by darlenedms** [comment]
A ideia inicial não era deixar o rodapé sempre fixo, era apenas pro rodapé não ficar flutuando no caso do conteúdo da página ser menor que o viewport mas acredito que pode fechar sim. :smile:

**Comment by dayanyrec** [comment]
Acho que fica bacana como tá. :smiley:
