### ISSUE TITLE
Ajudar na melhoria do projeto

### ISSUE THREAD

**Issue by carmemdeandrade** [insideoutprojectbr/mulheres-palestrantes#91]
Oi meninas, não sei como está o planejamento de vocês para evoluir o projeto, mas eu sou designer de interfaces e gostaria de ajudar voluntariamente. Se tiverem interesse podem mandar um email para carmemgeorgia@gmail.com.

**Comment by darlenedms** [comment]
Olá, @carmemdeandrade. Sua ajuda é muito bem-vinda! Precisamos mesmo de uma designer pra contribuir. 😍  Entraremos em contato.
